// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import ()

type FriendRequest struct {
	ID         int32
	SenderID   int32
	ReceiverID int32
	Status     string
}

type User struct {
	ID           int32
	Username     string
	Firstname    string
	Lastname     string
	Passwordhash string
}
